### ISSUE TITLE
what's the mean of "patent_num"? which columns is it responsing to in Google Patent?

### ISSUE THREAD

**Issue by YuhangWang-Fishtank** [KPSS2017/Technological-Innovation-Resource-Allocation-and-Growth-Extended-Data#2]
Thank you for your outstanding work. 

But I am confused about the meaning of columns when using data. May I ask which column in the Google patent corresponds to 'patent_num'?

**Comment by KPSS2017** [comment]
Hi, thanks for asking. `patent_num` is the patent identification number. In Google patent, that's the number you see at the top right blue block. For example, a patent with ID number 9999999 can be found in https://patents.google.com/patent/US9999999.
