### ISSUE TITLE
cannot download data with clone repository

### ISSUE THREAD

**Issue by zww200208** [KPSS2017/Technological-Innovation-Resource-Allocation-and-Growth-Extended-Data#7]
I tried to use git clone the repository, however, the zipper folders are all empty. Can anyone help on this issue?

**Comment by mrcljns** [comment]
I know this reply is late, but in order to fix this issue you need to use git lfs (large files storage). Open your local cloned repo in the console and run "git lfs pull". Your zip files should now have the appropriate size. Hope this helps!
